"""
Phase 2 Trainer: YOLO-Centric Fine-Tuning.

This script trains the EfficientNet-B5 model on the 'Cleaned' dataset
generated by the YOLO Processor. It focuses the model on food texture
by utilizing cropped, background-free images.
"""

import os
import tensorflow as tf
import keras
from keras import callbacks, optimizers, losses, metrics
from pathlib import Path

# Local Imports
from src import config
from src.vision_model import build_model
from src.augmentation import RandomGaussianBlur

# ==============================================================================
# CONFIGURATION OVERRIDES
# ==============================================================================
# We point to the new YOLO-processed dataset
YOLO_DATA_DIR = config.DATA_DIR / "yolo_processed"
TRAIN_DIR = YOLO_DATA_DIR / "train"
VAL_DIR = YOLO_DATA_DIR / "val"

# Output Model Name (Safe from overwriting original)
CHECKPOINT_PATH = config.CHECKPOINT_DIR / "model_yolo_best.keras"

def get_dataset(directory, subset_name):
    """
    Loads and configures the dataset pipeline.
    """
    if not directory.exists():
        raise FileNotFoundError(f"Dataset not found at {directory}. Run 'src/data_tools/yolo_processor.py' first.")

    ds = keras.utils.image_dataset_from_directory(
        directory,
        labels="inferred",
        label_mode="categorical",
        class_names=None, # Inferred from subdirectories
        color_mode="rgb",
        batch_size=config.BATCH_SIZE,
        image_size=config.IMG_SIZE,
        shuffle=True,
        seed=config.SEED,
        interpolation="bilinear"
    )
    return ds

def build_augmentation_layer():
    """
    Constructs the augmentation pipeline.
    Critically includes RandomGaussianBlur to simulate focus blur.
    """
    return keras.Sequential([
        keras.layers.RandomFlip("horizontal_and_vertical"),
        keras.layers.RandomRotation(0.2),
        keras.layers.RandomZoom(0.1),
        keras.layers.RandomContrast(0.1),
        # Custom Augmentation from src.augmentation
        RandomGaussianBlur(kernel_size=3, probability=0.5)
    ], name="data_augmentation")

def main():
    print(f"🚀 Starting YOLO-Centric Training Pipeline")
    print(f"📂 Data Source: {YOLO_DATA_DIR}")
    
    # 1. Load Data
    train_ds = get_dataset(TRAIN_DIR, "Training")
    val_ds = get_dataset(VAL_DIR, "Validation")

    # Get number of classes
    class_names = train_ds.class_names
    num_classes = len(class_names)
    print(f"ℹ️ Found {num_classes} classes: {class_names[:5]}...")

    # 2. Performance Optimization (Prefetching)
    AUTOTUNE = tf.data.AUTOTUNE
    train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
    val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

    # 3. Build Model
    # Note: We build a fresh model. If you want to resume, load weights here.
    base_model = build_model(num_classes)
    
    # Inject Augmentation Layer
    # We wrap the model to include augmentation during training only
    inputs = keras.Input(shape=config.INPUT_SHAPE)
    x = build_augmentation_layer()(inputs)
    outputs = base_model(x)
    final_model = keras.Model(inputs, outputs, name="FoodVision_YOLO_B5")

    # 4. Compile
    optimizer = optimizers.AdamW(
        learning_rate=config.LEARNING_RATE,
        weight_decay=config.WEIGHT_DECAY
    )
    
    final_model.compile(
        optimizer=optimizer,
        loss=losses.CategoricalCrossentropy(label_smoothing=0.1),
        metrics=[
            metrics.CategoricalAccuracy(name="accuracy"),
            metrics.TopKCategoricalAccuracy(k=3, name="top_3_accuracy")
        ]
    )

    # 5. Callbacks
    my_callbacks = [
        callbacks.ModelCheckpoint(
            filepath=str(CHECKPOINT_PATH),
            save_best_only=True,
            monitor="val_accuracy",
            mode="max",
            verbose=1
        ),
        callbacks.EarlyStopping(
            monitor="val_loss",
            patience=5,
            restore_best_weights=True,
            verbose=1
        ),
        callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.2,
            patience=3,
            min_lr=1e-6,
            verbose=1
        ),
        # TensorBoard logging could be added here
        callbacks.CSVLogger(str(config.PROCESSED_DIR / "training_log_yolo.csv"))
    ]

    # 6. Train
    print("🔥 Beginning Training...")
    history = final_model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=30, # Adjustable
        callbacks=my_callbacks
    )
    
    print(f"✅ Training Complete. Best model saved to: {CHECKPOINT_PATH}")

if __name__ == "__main__":
    # Ensure directories exist
    os.makedirs(config.CHECKPOINT_DIR, exist_ok=True)
    main()